"""create study_sessions table

Revision ID: 112a728da308
Revises: 
Create Date: 2026-04-03 17:25:45.444135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112a728da308'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_type', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=True),
    sa.Column('topic', sa.String(length=512), nullable=True),
    sa.Column('score_avg', sa.Float(), nullable=True),
    sa.Column('num_questions', sa.Integer(), nullable=True),
    sa.Column('num_correct', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_session_type'), 'study_sessions', ['session_type'], unique=False)
    op.create_index(op.f('ix_study_sessions_subject'), 'study_sessions', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_sessions_subject'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_session_type'), table_name='study_sessions')
    op.drop_table('study_sessions')
    # ### end Alembic commands ###
